#!/usr/bin/env python3
"""
Example: Embedding HTML in a Typst template using Python
"""

import sys
sys.path.insert(0, '..')
from html2typst import html_to_typst

# Your HTML content (could be loaded from a file, database, API, etc.)
html_content = """
<h2>Introduction</h2>
<p>This section was generated from <strong>HTML</strong> and embedded into a Typst template.</p>

<h3>Key Points</h3>
<ul>
  <li>HTML is converted to Typst automatically</li>
  <li>Templates can be filled programmatically</li>
  <li>No manual conversion needed</li>
</ul>

<h3>Code Example</h3>
<p>Here's how you would use it:</p>
<pre>
from html2typst import html_to_typst
result = html_to_typst(html)
</pre>
"""

# Convert HTML to Typst
converted_content = html_to_typst(html_content)

# Create a Typst document with the converted content
typst_document = f"""
#set document(title: "Generated Report")
#set page(
  paper: "a4",
  margin: (x: 1.5cm, y: 2cm),
  numbering: "1",
)
#set text(
  font: "Linux Libertine",
  size: 11pt,
)

= My Generated Document

This is the header of my template.

{converted_content}

= Conclusion

This content was automatically generated by combining a Typst template with HTML content.
"""

# Write the final document
output_file = 'generated-document.typ'
with open(output_file, 'w') as f:
    f.write(typst_document)

print(f"✓ Successfully generated: {output_file}")
print(f"\nTo compile with Typst:")
print(f"  typst compile {output_file}")
