
#set document(title: "Generated Report")
#set page(
  paper: "a4",
  margin: (x: 1.5cm, y: 2cm),
  numbering: "1",
)
#set text(
  font: "Linux Libertine",
  size: 11pt,
)

= My Generated Document

This is the header of my template.

== Introduction

This section was generated from *HTML* and embedded into a Typst template.
=== Key Points

- HTML is converted to Typst automatically
- Templates can be filled programmatically
- No manual conversion needed

=== Code Example

Here's how you would use it:
```
from html2typst import html_to_typst
result = html_to_typst(html)
```

= Conclusion

This content was automatically generated by combining a Typst template with HTML content.
